### ISSUE TITLE
Mod updates despite config changes telling it to not do so/Duplicated mods on auto-update

### ISSUE THREAD

**Issue by BarbasTheDog** [MSourceCoded/SourceCodedCore#3]
Even after changing the "vers_auto" config to false, the mod still auto-updates itself. That not only is an issue by itself, but the mod also doesnt delete the old version, causing a duplicated mod error.

You may notice that I made a pull request a few hours ago and in the begining I thought the fact that it was set to "true" by default was the only issue. It can easily be ignored :P 

(I still think it should be disabled by default though)

**Comment by MSourceCoded** [comment]
Exiting the game normally should cause the Cleanup.jar program to launch, cleaning up the old version. 

As for the vers_auto thing, that won't download a new version, but instead will only notify you that a new version is available.

**Comment by BarbasTheDog** [comment]
oh? I'm sorry for all this conusion. We were in the process of updating thr pack when SourceCodedCore updated, so that probably didn't help too.

Again, sorry for all this. :/

**Comment by MSourceCoded** [comment]
Don't worry. Version Updating was removed in the latest patch but it might come back in 1.8 when it becomes a coremod
